config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'search', to: 'pages#search'

  resources :users do
    resource :profile_pages
    resource :mail_boxes do
      resource :messages
    end
    resources :organizations, shallow: true
    resources  :organization_invitations, shallow: true
    resources :events, shallow: true
    resources  :event_invitations, shallow: true
    resources :notifications
  end

  resources :organizations do
    resources :organization_invitations
  end

  resources :events do
    resources :comments
    resources :event_invitations
    resources :event_dates
  end

  resources :event_invitations do
    resources :user_votes
  end

  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :events do
        resources :comments, shallow: true
      end
    end
  end

  namespace :admin do
    resources :organizations, :users
    resources :events do
      resources :comments
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event_invitation
  belongs_to :event
  has_many_attached :comment_images
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :set_admin_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /admin/comments
  # GET /admin/comments.json
  def index
    @admin_comments = Comment.all.where("event_id = ?", params[:event_id])
    @event=Event.find(params[:event_id])
  end

  # GET /admin/comments/1
  # GET /admin/comments/1.json
  def show
  end

  # GET /admin/comments/new
  def new
    @admin_comment = Comment.new
    @admin_event = Event.find(params[:event_id])
  end

  # GET /admin/comments/1/edit
  def edit
    @admin_event = Event.find(@admin_comment.event.id)
  end

  # POST /admin/comments
  # POST /admin/comments.json
  def create
    if params[:comment][:user_id].nil?
      redirect_back(fallback_location: root_path)
      flash[:alert] = "No user selected"
    else
      @admin_comment = Comment.new(admin_comment_params)
      @admin_comment.event_invitation = EventInvitation.find_by(user_id: params[:comment][:user_id], event_id: params[:event_id])
      @admin_comment.event =Event.find(params[:event_id])
      respond_to do |format|
        if @admin_comment.save
          format.html { redirect_to admin_event_comments_path(params[:event_id]), notice: 'Comment was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end
  end

  # PATCH/PUT /admin/comments/1
  # PATCH/PUT /admin/comments/1.json
  def update
    respond_to do |format|
      if @admin_comment.update(admin_comment_params)
        format.html { redirect_to admin_event_comments_path(@admin_comment.event.id), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_comment }
      else
        format.html { render :edit }
        format.json { render json: @admin_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/comments/1
  # DELETE /admin/comments/1.json
  def destroy
    @admin_comment.destroy
    respond_to do |format|
      format.html { redirect_to admin_event_comments_path(params[:event_id]), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_comment
      @admin_comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_comment_params
      params.fetch(:comment, {}).permit(:id, :content)
    end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApiController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Event.find(params[:event_id]).comments
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.event = Event.find(params[:event_id])
    @comment.event_invitation = EventInvitation.find(params[:event_invitation_id])

    respond_to do |format|
      if @comment.save
        format.json { render :show, status: :created, location: api_v1_comment_path(@comment) }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.json { render :show, status: :ok, location: api_v1_comment_path(@comment) }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    respond_to do |format|
      if @comment.destroy
        format.json { head :no_content }
      else
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.fetch(:comment, {}).permit(:id, :content, :commented_id, :event_invitation_id, :event_id, :created_at, :updated_at)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Event.find(params[:event_id]).comments.where("commented_id IS NULL")
    @event = Event.find(params[:event_id])
    @users =[]
    @comments.each do |comment|
      @users.append(Comment.find(comment.id).event_invitation.user)
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])
    @replies_comments = Comment.all.where("commented_id = ?", params[:id])
    @users =[]
    @replies_comments.each do |comment|
      @users.append(Comment.find(comment.id).event_invitation.user)
      end
  end

  # GET /comments/new
  def new
    @event= Event.find(params[:event_id])

    if current_user.id == Event.find(params[:event_id]).user.id
      redirect_back(fallback_location: root_path)
      flash[:alert] = "The event creator can't comment his own event"
    end

    @comment = Comment.new()
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @event_invitation = EventInvitation.where("user_id = ? AND event_id = ?", current_user.id, params[:event_id]).first
    @comment = Comment.new(comment_params)
    @comment.event_invitation = @event_invitation
    @comment.event = Event.find(params[:event_id])
    respond_to do |format|
      if @comment.save
        format.html { redirect_to event_comments_path(params[:event_id]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.fetch(:comment, {}).permit(:id, :content, :commented_id, :reply, comment_images: [] )
    end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_form.html.erb
<%= form_with(model: [:admin, @admin_event ,@admin_comment], local: true) do |form| %>
  <% if @admin_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_comment.errors.count, "error") %> prohibited this admin_comment from being saved:</h2>

      <ul>
        <% @admin_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">

    <div class="form-group">
      <%= form.label :content %>
      <%= form.text_area :content, class: "form-control" %>
    </div>
    <% if action_name == 'new' %>
      <div class="form-group">
        <%= form.label :user %>
        <%= form.collection_select(:user_id, Event.find(@admin_event.id).users, :id, :username, {}, { class: "form-control" }) %>
      </div>
    <% end %>
    <%= form.submit class:"btn btn-primary mt-3" %>
    <%= link_to "Back", admin_event_comments_path(@admin_event), class: ["btn", "btn-secondary mt-3"] %>

  </div>
<% end %>

app/views/admin/comments/edit.html.erb
<h1>Editing Admin Comment</h1>

<%= render 'form', locals: {admin_event: @admin_event,admin_comment: @admin_comment} %>

app/views/admin/comments/index.html.erb
<h1 class="mb-5">Comments Administration<%= link_to 'New Comment', new_admin_event_comment_path(@event), class:"btn btn-info btn-sm mx-3"  %></h1>

<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th>N</th>
      <th>Comment</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <%@counter=1 %>
    <% @admin_comments.each do |admin_comment| %>
      <tr>
        <td><%= @counter %></td>
        <td style="width: 50%"><%= admin_comment.event_invitation.user.username %> says: <%= admin_comment.content %></td>
        <td><%= link_to 'Edit', edit_admin_event_comment_path(admin_comment.event.id, admin_comment), class:"btn btn-primary btn-sm mr-2" %><%= link_to 'Destroy', admin_event_comment_path(admin_comment.event.id, admin_comment), method: :delete, class:"btn btn-danger btn-sm" %></td>
      </tr>
      <% @counter+=1 %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/comments/new.html.erb
<h1>New Admin Comment</h1>

<%= render 'form', locals: {admin_event: @admin_event,admin_comment: @admin_comment, a:"new"} %>

app/views/admin/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_comment_path(@admin_comment) %> |
<%= link_to 'Back', admin_comments_path %>