config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'search', to: 'pages#search'

  resources :users do
    resource :profile_pages
    resource :mail_boxes do
      resource :messages
    end
    resources :organizations, shallow: true
    resources  :organization_invitations, shallow: true
    resources :events, shallow: true
    resources  :event_invitations, shallow: true
    resources :notifications
  end

  resources :organizations do
    resources :organization_invitations
  end

  resources :events do
    resources :comments
    resources :event_invitations
    resources :event_dates
  end

  resources :event_invitations do
    resources :user_votes
  end

  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :events do
        resources :comments, shallow: true
      end
    end
  end

  namespace :admin do
    resources :organizations, :users
    resources :events do
      resources :comments
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organization, optional: true
  belongs_to :user
  has_many :event_invitations, :dependent => :destroy
  has_many :users, :through => :event_invitations
  has_many :event_dates, :dependent => :destroy
  has_many :user_votes, :through => :event_dates
  has_many :comments, :dependent => :destroy
  has_one_attached :event_picture
  has_many_attached :documents
  has_many_attached :videos
  has_many_attached :images
  accepts_nested_attributes_for :event_invitations, allow_destroy: true

  after_initialize :default_values
  before_update :send_notification, :if => :start_event_date_vote_changed?


  private
  def default_values
    self.hidden ||= false
  end

  def send_notification
    self.event_invitations.each do |invitation|
      Notification.create(user_id: invitation.user_id, notification_type: 1, event_id: self.id)
    end
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  before_action :set_admin_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /admin/events
  # GET /admin/events.json
  def index
    @admin_events = Event.all
  end

  # GET /admin/events/1
  # GET /admin/events/1.json
  def show
  end

  # GET /admin/events/new
  def new
    @admin_event = Event.new
  end

  # GET /admin/events/1/edit
  def edit
  end

  # POST /admin/events
  # POST /admin/events.json
  def create
    @admin_event = Event.new(admin_event_params)
    @admin_event.user = User.find(params[:event][:user_id])

    respond_to do |format|
      if @admin_event.save
        format.html { redirect_to admin_events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @admin_event }
      else
        format.html { render :new }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/events/1
  # PATCH/PUT /admin/events/1.json
  def update
    respond_to do |format|
      if @admin_event.update(admin_event_params)
        format.html { redirect_to admin_events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_event }
      else
        format.html { render :edit }
        format.json { render json: @admin_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/events/1
  # DELETE /admin/events/1.json
  def destroy
    @admin_event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_event
      @admin_event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_event_params
      params.fetch(:event, {}).permit(:id, :title, :description, :location, :event_picture, :user_id,
                                            documents: [], videos: [], images: [])
    end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApiController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = User.find(params[:user_id])

    respond_to do |format|
      if @event.save
        format.json { render :show, status: :created, location: api_v1_event_path(@event) }
      else
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.json { render :show, status: :ok, location: @event }
      else
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(:user_id, :organization_id, :location, :minimum_guest, :start_event_date_vote, :event_rule, :hidden, :banner_picture, :title, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource :user
  load_and_authorize_resource :event

  # GET /events
  # GET /events.json
  def index
    @events = Event.all.where("user_id = ?", params[:user_id])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create

    @event = Event.new(event_params)
    @event.user_id = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.start_event_date_vote = params[:start_event_date_vote]
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    begin
      @event.destroy
      redirect_back(fallback_location: root_path)
      flash[:notice] = "The event has been deleted"
    rescue
      flash[:alert] = "Could not delete the event!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(:title, :description, :location, :event_picture, :organization_id,
                                      event_invitations_attributes: [:id, :_destroy], documents: [],
                                      videos: [], images: [])
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<div class="row ml-0">
  <%= form_with model: [:admin, @admin_event], local: true do |form| %>
    <% if @admin_event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@admin_event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% @admin_event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :location %>
      <%= form.text_field :location, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :event_picture %>
      <br>
      <%= form.file_field :event_picture %>
    </div>
    <div class="form-group">
      <%= form.label :documents %>
      <br>
      <%= form.file_field :documents, multiple: true %>
    </div>
    <div class="form-group">
      <%= form.label :videos %>
      <br>
      <%= form.file_field :videos, multiple: true %>
    </div>
    <div class="form-group">
      <%= form.label :images %>
      <br>
      <%= form.file_field :images, multiple: true %>
    </div>

    <% if action_name == 'new' %>
      <div class="form-group">
        <%= form.label :user %>
        <%= form.collection_select(:user_id, User.all.order(username: :asc), :id, :username, {}, { class: "form-control" }) %>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.submit class:"btn btn-primary mt-3"%>
    </div>
  <% end %>
</div>

app/views/admin/events/edit.html.erb
<h1>Editing Admin Event</h1>

<%= render 'form', admin_event: @admin_event %>

app/views/admin/events/index.html.erb
<h1 class="mb-5">Events Administration<%= link_to 'New Event', new_admin_event_path, class:"btn btn-info btn-sm mx-3"  %></h1>


<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th>N</th>
      <th>Name</th>
      <th>User creator</th>
      <th>Action</th>
      <th>CRUD Comments</th>
    </tr>
    </thead>
    <tbody>
    <%@counter=1 %>
    <% @admin_events.each do |admin_event| %>
      <tr>
        <td><%= @counter %></td>
        <td style="width: 30%"><%= admin_event.title %></td>
        <td>@<%= admin_event.user.username %></td>
        <td><%= link_to 'Show', admin_event, class:"btn btn-primary btn-sm" %><%= link_to 'Edit', edit_admin_event_path(admin_event),class:"btn btn-primary btn-sm mx-2" %><%= link_to 'Destroy', admin_event_path(admin_event), method: :delete, class:"btn btn-danger btn-sm" %></td>
        <td><%= link_to "Total comments: "+admin_event.comments.count.to_s, admin_event_comments_path(admin_event) %></td>
      </tr>
      <% @counter+=1 %>
    <% end %>
    </tbody>
  </table>
</div>

app/views/admin/events/new.html.erb
<h1>New Admin Event</h1>

<%= render 'form', admin_event: @admin_event %>

app/views/admin/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_event_path(@admin_event) %> |
<%= link_to 'Back', admin_events_path %>