config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'search', to: 'pages#search'

  resources :users do
    resource :profile_pages
    resource :mail_boxes do
      resource :messages
    end
    resources :organizations, shallow: true
    resources  :organization_invitations, shallow: true
    resources :events, shallow: true
    resources  :event_invitations, shallow: true
    resources :notifications
  end

  resources :organizations do
    resources :organization_invitations
  end

  resources :events do
    resources :comments
    resources :event_invitations
    resources :event_dates
  end

  resources :event_invitations do
    resources :user_votes
  end

  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :events do
        resources :comments, shallow: true
      end
    end
  end

  namespace :admin do
    resources :organizations, :users
    resources :events do
      resources :comments
    end
  end
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  belongs_to :event
  has_many :user_votes, :dependent => :destroy
end

app/controllers/event_dates_controller.rb
class EventDatesController < ApplicationController
  before_action :set_event_date, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource :event

  # GET /event_dates
  # GET /event_dates.json
  def index
    @event_dates = Event.find(params[:event_id]).event_dates
    @creator_user = Event.find(params[:event_id]).user
    @users_votes =[]
    @event_dates.each do |date|
      @users_votes.append(UserVote.where("event_date_id = ?", date).count)
    end
  end
  # GET /event_dates/1
  # GET /event_dates/1.json
  def show
  end

  # GET /event_dates/new
  def new
    @event = Event.find(params[:event_id])
    @event_date = EventDate.new
  end

  # GET /event_dates/1/edit
  def edit
  end

  # POST /event_dates
  # POST /event_dates.json
  def create
    @event_date = EventDate.new(event_date_params)
    @event = Event.find(params[:event_id])
    @event_date.event = @event

    respond_to do |format|
      if @event_date.save
        format.html { redirect_to event_event_dates_path(@event.id), notice: 'Event date was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /event_dates/1
  # PATCH/PUT /event_dates/1.json
  def update
    respond_to do |format|
      if @event_date.update(event_date_params)
        format.html { redirect_to @event_date, notice: 'Event date was successfully updated.' }
        format.json { render :show, status: :ok, location: @event_date }
      else
        format.html { render :edit }
        format.json { render json: @event_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_dates/1
  # DELETE /event_dates/1.json
  def destroy
    begin
      @event_date.destroy
      redirect_back(fallback_location: root_path)
      flash[:notice] = "The event date has been destroyed"
    rescue
      flash[:alert] = "Could not delete the event date!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_date
      @event_date = EventDate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_date_params
      params.fetch(:event_date, {}).permit(:event_date, :event_id)
    end
end

app/helpers/event_dates_helper.rb
module EventDatesHelper
end

app/views/event_dates/_form.html.erb
<%= form_with(model: [@event, @event_date], local: true) do |form| %>
  <% if @event_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_date.errors.count, "error") %> prohibited this event_date from being saved:</h2>

      <ul>
        <% @event_date.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :event_date %>
    <%= form.datetime_local_field :event_date %>
  </div>
  <div class="form-group">
    <%= form.submit class: ["btn", "btn-primary"] %>
    <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
  </div>
<% end %>

app/views/event_dates/edit.html.erb
<h1>Editing Event Date</h1>

<%= render 'form', event_date: @event_date %>

<%= link_to 'Show', @event_date %> |
<%= link_to 'Back', event_dates_path %>

app/views/event_dates/index.html.erb
<h1>Event Dates</h1>

<div class="container">
  <table class="table">
    <thead>
    <tr>
      <th>Date</th>
      <th>Number of Votes</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @event_dates.zip(@users_votes).each do |event_date, vote|%>
      <tr>
        <td><%= event_date.event_date %></td>
        <td><%= vote %></td>
        <td><%= link_to 'Select', event_path(event_date.event.id, :start_event_date_vote => event_date.event_date), class: 'btn btn-secondary btn-sm', data: { confirm: "Use this date for the event?" }, method: :put %>
          <%= link_to 'Destroy', event_event_date_path(event_date.event.id, event_date.id), class: 'btn btn-danger btn-sm', method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Create', new_event_event_date_path(), class: 'btn btn-primary'%>
<%= link_to 'Back', user_events_path(@creator_user), class: 'btn btn-secondary'%>

app/views/event_dates/new.html.erb
<h1>New Event Date</h1>

<%= render 'form', locals: { event: @event, event_dates: @event_date } %>

app/views/event_dates/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_date_path(@event_date) %> |
<%= link_to 'Back', event_dates_path %>