config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'search', to: 'pages#search'

  resources :users do
    resource :profile_pages
    resource :mail_boxes do
      resource :messages
    end
    resources :organizations, shallow: true
    resources  :organization_invitations, shallow: true
    resources :events, shallow: true
    resources  :event_invitations, shallow: true
    resources :notifications
  end

  resources :organizations do
    resources :organization_invitations
  end

  resources :events do
    resources :comments
    resources :event_invitations
    resources :event_dates
  end

  resources :event_invitations do
    resources :user_votes
  end

  namespace :api, defaults: { format: :json} do
    namespace :v1 do
      resources :events do
        resources :comments, shallow: true
      end
    end
  end

  namespace :admin do
    resources :organizations, :users
    resources :events do
      resources :comments
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
  has_many :organization_invitations, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :users, :through => :organization_invitations
  has_one_attached :organization_picture
  has_many_attached :documents
  has_many_attached :videos
  has_many_attached :images
  accepts_nested_attributes_for :organization_invitations, allow_destroy: true
  accepts_nested_attributes_for :user

end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < ApplicationController
  before_action :set_admin_organization, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!

  # GET /admin/organizations
  # GET /admin/organizations.json
  def index
    @admin_organizations = Organization.all
  end

  # GET /admin/organizations/1
  # GET /admin/organizations/1.json
  def show
  end

  # GET /admin/organizations/new
  def new
    @admin_organization = Organization.new
  end

  # GET /admin/organizations/1/edit
  def edit
  end

  # POST /admin/organizations
  # POST /admin/organizations.json
  def create
    @admin_organization = Organization.new(admin_organization_params)
    @admin_organization.user = User.find(params[:organization][:user_id])

    respond_to do |format|
      if @admin_organization.save
        format.html { redirect_to admin_organizations_path, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @admin_organization }
      else
        format.html { render :new }
        format.json { render json: @admin_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/organizations/1
  # PATCH/PUT /admin/organizations/1.json
  def update
    respond_to do |format|
      if @admin_organization.update(admin_organization_params)
        format.html { redirect_to admin_organizations_path, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_organization }
      else
        format.html { render :edit }
        format.json { render json: @admin_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/organizations/1
  # DELETE /admin/organizations/1.json
  def destroy
    @admin_organization.destroy
    respond_to do |format|
      format.html { redirect_to admin_organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_organization
      @admin_organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_organization_params
      params.fetch(:organization, {}).permit(:id, :name, :description, :banner_picture, :organization_picture,
                                             documents: [], videos: [], images: [] )
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  load_and_authorize_resource :user

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all.where("user_id = ?", params[:user_id])
    @admin_invitation = OrganizationInvitation.all.where("user_id = ? AND admin = ?", params[:user_id],true)
    @admin=[]
    @admin_invitation.each do |j|
      @temp = Organization.where("id = ?", j.organization_id)
      @temp.each do |t|
        @admin.append(t)
        end
    end
  end


  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @events_organization = Event.all.where("organization_id = ? AND hidden = 0", params[:id])
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)
    @organization.user_id = current_user.id

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.fetch(:organization, {}).permit(:id, :name, :description, :organization_picture,
                                             documents: [], videos: [], images: [],
                                             organization_invitations_attributes: [:id, :_destroy])
    end
end

app/helpers/admin/organizations_helper.rb
module Admin::OrganizationsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: @organization, local: true) do |form| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :organization_picture %>
      <br>
      <%= form.file_field :organization_picture %>
    </div>
    <div class="form-group">
      <%= form.label :documents %>
      <br>
      <%= form.file_field :documents, multiple: true %>
    </div>
    <div class="form-group">
      <%= form.label :videos %>
      <br>
      <%= form.file_field :videos, multiple: true %>
    </div>
    <div class="form-group">
      <%= form.label :images %>
      <br>
      <%= form.file_field :images, multiple: true %>
    </div>
    <% if params[:action] == 'edit' %>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title"> Delete Invitation To: </h5>
          <hr>
          <%=form.fields_for :organization_invitations do |organization_invitations_form| %>
            <div class="form-group">
              <% if action_name == 'edit' %>
                <%= organization_invitations_form.label organization_invitations_form.object.user.username %>
                <%= organization_invitations_form.check_box :_destroy %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>

      <% end %>

    <%= form.submit class: ["btn", "btn-primary", "mt-3"]%>
    <%= link_to "Back", :back, class: ["btn", "btn-secondary", "mt-3"] %>
  </div>
<% end %>

app/views/organizations/_organization_tile.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm">
    <%if organization.organization_picture.attached? %>
      <%= link_to image_tag(organization.organization_picture, class: "card-img-top", width: "100%"), url_for(organization) %>
    <%else %>
      <img src="https://748073e22e8db794416a-cc51ef6b37841580002827d4d94d19b6.ssl.cf3.rackcdn.com/not-found.png" class="card-img-top"  height="230px">
    <% end %>
    <div class="card-body">
      <p class="card-text font-italic text-center"><%= link_to organization.name , organization %></p>
      <div class="card mx-1 mb-3 bg-secondary" ></div>
      <p class="card-text mb-2 text-muted"><%= "Creation: " + organization.created_at.strftime("%d %h %Y at %I:%M%p") %></p>
      <p class="card-text text-muted"><%="Description: " + organization.description %></p>
      <div class="d-flex justify-content-between align-items-center">
        <%if a == "my_organizations" %>
            <a href="<%= organization_path(organization.id) %>" class="btn btn-primary btn-sm ml-auto">View</a>
            <a href="<%= edit_organization_path(organization.id) %>" class="btn btn-primary btn-sm mx-1">Edit</a>
            <a href="<%= new_organization_organization_invitation_path(organization.id) %>" class="btn btn-primary btn-sm mx-1">Invite</a>
            <%= link_to 'Destroy', organization_path(organization.id), class: 'btn btn-danger btn-sm md-auto', method: :delete %>
          <%elsif a == "organization_member"%>
          <a href="<%= organization_path(organization.id) %>" class="btn btn-primary">View</a>
        <%end %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render "form", local: @organization %>

app/views/organizations/index.html.erb
<h1>My Organizations<%= link_to 'Create New Organization', new_user_organization_path(current_user.id), class:"btn btn-info btn-sm mx-3"%></h1>
<br>
<h3 class="mb-4">My Created Organizations</h3>
<% if @organizations != []%>
  <div class="row">
    <% @organizations.each do |organization| %>
      <%= render partial: 'organization_tile', locals: { organization: organization, a: "my_organizations"} %>
    <% end %>
  </div>
<%else %>
  <p>You have not create an organization yet</p>
<% end %>

<br>
<h3>Organization where I am admin</h3>
<% if @admin != []%>
  <div class="row">
    <% @admin.each do |organization| %>
      <%= render partial: 'organization_tile', locals: { organization: organization, a: "my_organizations"} %>
    <% end %>
  </div>
<% else %>
  <p>You are not admin of any organization :(</p>
<% end %>





</tbody>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

app/views/organizations/show.html.erb
<div class="row mb-2" >
  <div class="col-md-5">
    <div class="profile-pic text-center">
      <% if @organization.organization_picture.attached? %>
        <div data-toggle="modal" data-target="#exampleModal" style="width:400px; hight:auto">
          <%= image_tag(@organization.organization_picture, class:"rounded", style:"width:100%") %>
        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content" style="width:800px">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"><%=@organization.name + ' Banner Picture' %></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body" style="width:800px; hight:auto">
                <%= image_tag(@organization.organization_picture, style:"width:100%") %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      <%else %>
        <img src="https://748073e22e8db794416a-cc51ef6b37841580002827d4d94d19b6.ssl.cf3.rackcdn.com/not-found.png"  width="380px" height="250px">
      <% end %>
    </div>
  </div>

  <div class="col-md-7">
    <div class="profile-info">
      <h3 class="display-3"><%= @organization.name%></h3><br>
      <p class="font-italic"><b>Creation: </b><%= @organization.created_at.strftime("%d %h %Y at %I:%M%p")  %></p>
      <p class="font-italic"><b>Description: </b><%= @organization.description  %></p><br>
      <%if @organization.images.attached? %>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#img">Image gallery</button>
      <%end %>
      <%if @organization.videos.attached? %>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#videos">Videos</button>
      <%end %>
      <%if @organization.documents.attached? %>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#info">Documentation</button>
      <%end %>
    </div>
  </div>
</div>

<div class="card my-3 bg-secondary" ></div>

<div id="img" class="collapse">
  <div class="row">
    <%= render partial: 'events/slide_show', locals: { event: @organization, title: "Images Uploaded"} %>
  </div>
  <div class="card mx-5 mb-3 bg-secondary" ></div>
</div>

<div id="videos" class="collapse">
  <div class="row">
    <div class="container-fluid">
      <h3 class="text-center mt-3">Videos Uploaded</h3>
      <div class="row">
        <% (0...@organization.videos.count).each do |video|  %>
          <video width="320" height="240" controls>
            <source src=<%= rails_blob_path(@organization.videos[video]) %> type="video/webm" />
          </video>
        <% end %>
      </div>
    </div>
  </div>
  <div class="card mx-5 mb-3 bg-secondary" ></div>
</div>

<div id="info" class="collapse">
  <div class="row">
    <div class="container-fluid">
      <h3 class="text-center mb-3 mt-2">Documentation Uploaded</h3>
      <table class="table">
        <thead>
        <tr>
          <th>Number</th>
          <th>File</th>
        </tr>
        </thead>
        <tbody>
        <% (0...@organization.documents.count).each do |doc|  %>
          <tr>
            <td><%= (doc+1).to_s %></td>
            <td><%= link_to "Document", rails_blob_path(@organization.documents[doc]), target: :_blank %></td>
          </tr>
        <%end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<h3>Organization Public Events</h3>
<% if @events_organization != []%>
  <div class="row">
    <% @events_organization.each do |event| %>
      <%= render partial: 'events/event_tile', locals: { event: event, a: "m"} %>
    <% end %>
  </div>
<% else %>
  <p>This organization doesn't have any public event :(</p>
<% end %>

<br>